package com.salesforce.deploy;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class CodeCoverage implements FileWriteable{ 
    public void run() throws IOException { 
        FileWriter fstream = new FileWriter("logs\\CodeCoverage.xsl");
        BufferedWriter out = new BufferedWriter(fstream);
        out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>");
        out.newLine();
        out.write("<!-- Edited by XMLSpy� -->");
        out.newLine();
        out.write("<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">");
        out.newLine();
        out.write("  <xsl:template match=\"/\">");
        out.newLine();
        out.write("    <html>");
        out.newLine();
        out.write("      <head>");
        out.newLine();
        out.write("        <title>Code coverage</title>");
        out.newLine();
        out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Tabs.css\"");
        out.newLine();
        out.write("             title=\"Style\"/>");
        out.newLine();
        out.write("      </head>");
        out.newLine();
        out.write("      <body>");
        out.newLine();
        out.write("        <div id=\"menu\">");
        out.newLine();
        out.write("          <ul>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"resume.xml\" title=\"Resume\">Resume</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"unitTest.xml\" title=\"Unit Test\">Unit Test</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"codeCoverage.xml\" title=\"Code Coverage\"  class=\"active\">Code Coverage</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("          </ul>");
        out.newLine();
        out.write("        </div>");
        out.newLine();
        out.write("        <div id=\"main\">");
        out.newLine();
        out.write("          <br/>");
        out.newLine();
        out.write("          <table  width=\"100%\">");
        out.newLine();
        out.write("            <tr>");
        out.newLine();
        out.write("              <h2>Code Coverage Class</h2>");
        out.newLine();
        out.write("            </tr>");
        out.newLine();
        out.write("            <tr>");
        out.newLine();
        out.write("              <table border=\"1\"  width=\"100%\">");
        out.newLine();
        out.write("                <tr bgcolor=\"#66CCFF\">");
        out.newLine();
        out.write("                  <th>Number</th>");
        out.newLine();
        out.write("                  <th>Class</th>");
        out.newLine();
        out.write("                  <th>Code Coverage Class</th>");
        out.newLine();
        out.write("                </tr>");
        out.newLine();
        out.write("                <xsl:for-each select=\"results/codeCoverageClass/item\">");
        out.newLine();
        out.write("                  <tr bgcolor=\"{color}\">");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"number\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"class\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"percent\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                  </tr>");
        out.newLine();
        out.write("                </xsl:for-each>");
        out.newLine();
        out.write("              </table>");
        out.newLine();
        out.write("            </tr>");
        out.newLine();
        out.write("            <tr>");
        out.newLine();
        out.write("              <br/>");
        out.newLine();
        out.write("              <h3>Total Code coverage Classes: <xsl:value-of select=\"results/total/AvgCodeCoverageClass/item\" /> </h3>");
        out.newLine();
        out.write("              <br/>");
        out.newLine();
        out.write("              <br/>");
        out.newLine();
        out.write("              <br/>");
        out.newLine();
        out.write("              <h2>Code Coverage Triggers</h2>");
        out.newLine();
        out.write("            </tr>");
        out.newLine();
        out.write("            <tr>");
        out.newLine();
        out.write("              <table border=\"1\"  width=\"100%\">");
        out.newLine();
        out.write("                <tr bgcolor=\"#66CCFF\">");
        out.newLine();
        out.write("                  <th>Number</th>");
        out.newLine();
        out.write("                  <th>Trigger</th>");
        out.newLine();
        out.write("                  <th>Code Coverage Triggers</th>");
        out.newLine();
        out.write("                  <th>Code No coverage</th>");
        out.newLine();
        out.write("                </tr>");
        out.newLine();
        out.write("                <xsl:for-each select=\"results/codeCoverageTrigger/item\">");
        out.newLine();
        out.write("                  <tr bgcolor=\"{color}\">");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"number\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"trigger\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:value-of select=\"percent\" />");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                    <td>");
        out.newLine();
        out.write("                      <xsl:for-each select=\"location\">");
        out.newLine();
        out.write("                          <xsl:value-of select=\".\"/>");
        out.newLine();
        out.write("                          <br/>                        ");
        out.newLine();
        out.write("                      </xsl:for-each>");
        out.newLine();
        out.write("                    </td>");
        out.newLine();
        out.write("                  </tr>");
        out.newLine();
        out.write("                </xsl:for-each>");
        out.newLine();
        out.write("              </table>");
        out.newLine();
        out.write("              <br/>");
        out.newLine();
        out.write("              <h3>");
        out.newLine();
        out.write("                Total Code coverage Triggers: <xsl:value-of select=\"results/total/AvgCodeCoverageTrigger/item\" />");
        out.newLine();
        out.write("              </h3>");
        out.newLine();
        out.write("            </tr>       ");
        out.newLine();
        out.write("          </table>");
        out.newLine();
        out.write("        </div>");
        out.newLine();
        out.write("      </body>");
        out.newLine();
        out.write("    </html>");
        out.newLine();
        out.write("  </xsl:template>");
        out.newLine();
        out.write("</xsl:stylesheet>");
        out.newLine();
        out.close();
    }
}
