package com.salesforce.deploy;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class Tabs implements FileWriteable{ 
    public void run() throws IOException { 
        FileWriter fstream = new FileWriter("logs\\Tabs.css");
        BufferedWriter out = new BufferedWriter(fstream);
        out.write("ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,p,blockquote,fieldset,input");
        out.newLine();
        out.write("{");
        out.newLine();
        out.write("	margin: 0;");
        out.newLine();
        out.write("	padding: 0;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* HTML ELEMENTS */");
        out.newLine();
        out.write("body,html {");
        out.newLine();
        out.write("	padding-bottom:100px;");
        out.newLine();
        out.write("	font: 14px Georgia, serif;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("h1 {");
        out.newLine();
        out.write("	font: bold 65px/ 60px Helvetica, Arial, Sans-serif;");
        out.newLine();
        out.write("	text-align: center;");
        out.newLine();
        out.write("	color: #eee;");
        out.newLine();
        out.write("	text-shadow: 0px 2px 6px #333;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("h1 small {");
        out.newLine();
        out.write("	font-size: 20px;");
        out.newLine();
        out.write("	text-transform: uppercase;");
        out.newLine();
        out.write("	letter-spacing: 14px;");
        out.newLine();
        out.write("	display: block;");
        out.newLine();
        out.write("	color: #ccc;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("h2 a {");
        out.newLine();
        out.write("	display: block;");
        out.newLine();
        out.write("	text-decoration: none;");
        out.newLine();
        out.write("	margin: 0 0 30px 0;");
        out.newLine();
        out.write("	font: italic 45px Georgia, Times, Serif;");
        out.newLine();
        out.write("	text-align: center;");
        out.newLine();
        out.write("	color: #bfe1f1;");
        out.newLine();
        out.write("	text-shadow: 0px 2px 6px #333;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("h2 a:hover {");
        out.newLine();
        out.write("	color: #90bcd0;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("a {");
        out.newLine();
        out.write("	outline: none;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* COMMON CLASSES */");
        out.newLine();
        out.write(".break {");
        out.newLine();
        out.write("	clear: both;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* WRAPPER */");
        out.newLine();
        out.write("#wrapper {");
        out.newLine();
        out.write("	width: 800px;");
        out.newLine();
        out.write("	margin: 40px auto;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* CONTENT */");
        out.newLine();
        out.write("#content {");
        out.newLine();
        out.write("	");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("#content p {");
        out.newLine();
        out.write("	margin: 20px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* MENU */");
        out.newLine();
        out.write("#menu {");
        out.newLine();
        out.write("	margin: 40px 0 0 5%;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("#menu ul {");
        out.newLine();
        out.write("	list-style: none;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("#menu ul li {");
        out.newLine();
        out.write("	display: inline;");
        out.newLine();
        out.write("	float: left;");
        out.newLine();
        out.write("	margin-bottom: 20px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* :first-child pseudo selector with rounded top left corner */");
        out.newLine();
        out.write("#menu ul li:first-child a {");
        out.newLine();
        out.write("	-moz-border-radius-topleft: 12px;");
        out.newLine();
        out.write("	-webkit-border-top-left-radius: 12px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* :last-child pseudo selector with rounded top right corner */");
        out.newLine();
        out.write("#menu ul li:last-child a {");
        out.newLine();
        out.write("	-moz-border-radius-topright: 12px;");
        out.newLine();
        out.write("	-webkit-border-top-right-radius: 12px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* background color set to RGBA, with opacity on 0.3 and also using text-shadow */");
        out.newLine();
        out.write("#menu ul li a {");
        out.newLine();
        out.write("	padding: 20px;");
        out.newLine();
        out.write("	background: rgba(255, 138, 30, 0.3);");
        out.newLine();
        out.write("	text-decoration: none;");
        out.newLine();
        out.write("	font: bold 14px Helvetica, Sans-Serif;");
        out.newLine();
        out.write("	letter-spacing: -1px;");
        out.newLine();
        out.write("	color: #402e16;");
        out.newLine();
        out.write("	text-shadow: #eee 0px 0px 2px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* hover state shows a linear gradient and opacity it brought down to 0.9 and also shows a very slight grey gradient on top */");
        out.newLine();
        out.write("#menu ul li a:hover {");
        out.newLine();
        out.write("	-moz-box-shadow: 0 -5px 10px #777;");
        out.newLine();
        out.write("	-webkit-box-shadow: 0 -5px 10px #777;");
        out.newLine();
        out.write("	background: -webkit-gradient(linear, right bottom, left top, color-stop(0, rgb(237,");
        out.newLine();
        out.write("		227, 112) ), color-stop(0.72, rgb(255, 173, 10) ) ) !important;");
        out.newLine();
        out.write("	background: -moz-linear-gradient(right bottom, rgb(237, 227, 112) 0%,");
        out.newLine();
        out.write("		rgb(255, 173, 10) 72% ) !important;");
        out.newLine();
        out.write("	background-color: rgb(255, 173, 10) !important;");
        out.newLine();
        out.write("	-moz-opacity: .90;");
        out.newLine();
        out.write("	filter: alpha(opacity = 90);");
        out.newLine();
        out.write("	opacity: .90;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* another RGBA background, now with an opacity of 0.8 */");
        out.newLine();
        out.write("#menu ul li a.active {");
        out.newLine();
        out.write("	background: rgba(255, 138, 30, 0.8) !important;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* main contents with RGBA background (same colour as active tab) and three rounded corners */");
        out.newLine();
        out.write("#main {");
        out.newLine();
        out.write("	clear: both;");
        out.newLine();
        out.write("	background: rgba(255, 138, 30, 0.8);");
        out.newLine();
        out.write("	width: 90%;");
        out.newLine();
        out.write("	margin-left: 5%;");
        out.newLine();
        out.write("	-moz-border-radius-topright: 12px;");
        out.newLine();
        out.write("	-moz-border-radius-bottomright: 12px;");
        out.newLine();
        out.write("	-moz-border-radius-bottomleft: 12px;");
        out.newLine();
        out.write("	-webkit-border-top-right-radius: 12px;");
        out.newLine();
        out.write("	-webkit-border-bottom-right-radius: 12px;");
        out.newLine();
        out.write("	-webkit-border-bottom-left-radius: 12px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("/* header with a text-shadow */");
        out.newLine();
        out.write("#main h3 {");
        out.newLine();
        out.write("	text-transform: uppercase;");
        out.newLine();
        out.write("	padding: 20px 0 0 20px;");
        out.newLine();
        out.write("	color: #eee;");
        out.newLine();
        out.write("	text-shadow: #000 0px 0px 2px;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("");
        out.newLine();
        out.write("#main p {");
        out.newLine();
        out.write("	padding-bottom: 20px;");
        out.newLine();
        out.write("	color: #ddd;");
        out.newLine();
        out.write("}");
        out.newLine();
        out.close();
    }
}
