package com.salesforce.deploy;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class UnitTest implements FileWriteable{ 
    public void run() throws IOException { 
        FileWriter fstream = new FileWriter("logs\\UnitTest.xsl");
        BufferedWriter out = new BufferedWriter(fstream);
        out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>");
        out.newLine();
        out.write("<!-- Edited by XMLSpy� -->");
        out.newLine();
        out.write("<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">");
        out.newLine();
        out.write("  <xsl:template match=\"/\">");
        out.newLine();
        out.write("    <html>");
        out.newLine();
        out.write("      <head>");
        out.newLine();
        out.write("        <title>Unit Test</title>");
        out.newLine();
        out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Tabs.css\"");
        out.newLine();
        out.write("             title=\"Style\"/>");
        out.newLine();
        out.write("      </head>");
        out.newLine();
        out.write("      <body>");
        out.newLine();
        out.write("        <div id=\"menu\">");
        out.newLine();
        out.write("          <ul>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"resume.xml\" title=\"Resume\">Resume</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"unitTest.xml\" title=\"Unit Test\" class=\"active\">Unit Test</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("            <li>");
        out.newLine();
        out.write("              <a href=\"codeCoverage.xml\" title=\"Code Coverage\">Code Coverage</a>");
        out.newLine();
        out.write("            </li>");
        out.newLine();
        out.write("          </ul>");
        out.newLine();
        out.write("        </div>");
        out.newLine();
        out.write("        <div id=\"main\">");
        out.newLine();
        out.write("          <br/>");
        out.newLine();
        out.write("          <table>");
        out.newLine();
        out.write("          <tr>");
        out.newLine();
        out.write("            <h2>Failed unit test</h2>");
        out.newLine();
        out.write("          </tr>");
        out.newLine();
        out.write("          <tr>");
        out.newLine();
        out.write("            <table border=\"1\"  width=\"100%\">");
        out.newLine();
        out.write("              <tr bgcolor=\"#3399FF\">");
        out.newLine();
        out.write("                <th>Nro</th>");
        out.newLine();
        out.write("                <th>ID</th>");
        out.newLine();
        out.write("                <th>Class</th>");
        out.newLine();
        out.write("                <th>Method</th>");
        out.newLine();
        out.write("                <th>stackTrace</th>");
        out.newLine();
        out.write("              </tr>");
        out.newLine();
        out.write("              <xsl:for-each select=\"results/failures/item\">");
        out.newLine();
        out.write("                <tr  bgcolor=\"#FF7575\">");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"number\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"id\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"name\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"method\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"stackTrace\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                </tr>");
        out.newLine();
        out.write("              </xsl:for-each>");
        out.newLine();
        out.write("            </table>");
        out.newLine();
        out.write("          </tr>");
        out.newLine();
        out.write("          <tr>");
        out.newLine();
        out.write("            <br/>");
        out.newLine();
        out.write("          </tr>");
        out.newLine();
        out.write("          <tr>");
        out.newLine();
        out.write("            <h2>Success unit test</h2>");
        out.newLine();
        out.write("          </tr>");
        out.newLine();
        out.write("          <tr>");
        out.newLine();
        out.write("            <table border=\"1\"  width=\"100%\">");
        out.newLine();
        out.write("              <tr bgcolor=\"#3399FF\">");
        out.newLine();
        out.write("                <th>Nro</th>");
        out.newLine();
        out.write("                <th>ID</th>");
        out.newLine();
        out.write("                <th>Class</th>");
        out.newLine();
        out.write("                <th>Method</th>");
        out.newLine();
        out.write("              </tr>");
        out.newLine();
        out.write("              <xsl:for-each select=\"results/success/item\">");
        out.newLine();
        out.write("                <tr  bgcolor=\"#99FF99\">");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"number\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"id\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"name\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                  <td>");
        out.newLine();
        out.write("                    <xsl:value-of select=\"method\" />");
        out.newLine();
        out.write("                  </td>");
        out.newLine();
        out.write("                </tr>");
        out.newLine();
        out.write("              </xsl:for-each>");
        out.newLine();
        out.write("            </table>");
        out.newLine();
        out.write("          </tr>");
        out.newLine();
        out.write("          </table>");
        out.newLine();
        out.write("        </div>");
        out.newLine();
        out.write("      </body>");
        out.newLine();
        out.write("    </html>");
        out.newLine();
        out.write("  </xsl:template>");
        out.newLine();
        out.write("</xsl:stylesheet>");
        out.newLine();
        out.close();
    }
}
